# Generated by Django 3.0.7 on 2020-06-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название фото')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='производитель')),
                ('camera_model', models.CharField(max_length=50, verbose_name='модель камеры')),
                ('file_size', models.CharField(max_length=50, verbose_name='размер файла')),
                ('object_created', models.DateTimeField(auto_now_add=True, verbose_name='дата загрузки')),
                ('photo_created', models.CharField(max_length=50, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотки',
                'ordering': ['-object_created'],
            },
        ),
    ]
